# Generated by Django 3.0.4 on 2020-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChunkCascade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
