# Generated by Django 3.0.4 on 2020-03-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChunkCascade', '0003_auto_20200316_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
    ]
